import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, renameSync, rmSync, statSync, writeFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import path from "node:path";
const root = process.cwd(); const api = path.join(root, "app", "api"); const parked = path.join(root, "server", ".app-api-server-only");
const contentTypes = { ".css": "text/css; charset=utf-8", ".html": "text/html; charset=utf-8", ".ico": "image/x-icon", ".js": "text/javascript; charset=utf-8", ".json": "application/json; charset=utf-8", ".svg": "image/svg+xml", ".txt": "text/plain; charset=utf-8", ".woff2": "font/woff2" };
const mimeType = (file) => contentTypes[path.extname(file)] || "application/octet-stream";
function collectStaticFiles(directory, relative = "") { return readdirSync(directory).flatMap((entry) => { const full = path.join(directory, entry); const next = path.join(relative, entry); return statSync(full).isDirectory() ? collectStaticFiles(full, next) : [[`/${next.split(path.sep).join("/")}`, [mimeType(entry), readFileSync(full).toString("base64")]]]; }); }
function writeEmbeddedWorker(directory) {
  const files = Object.fromEntries(collectStaticFiles(directory));
  const source = `const files=${JSON.stringify(files)};
const decode=(value)=>Uint8Array.from(atob(value),character=>character.charCodeAt(0));
const json=(body,status=200)=>new Response(JSON.stringify(body),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'private, max-age=60'}});
const record=(value)=>value&&typeof value==='object'&&!Array.isArray(value)?value:{};
const text=(value)=>typeof value==='string'?value:'';
const safeUrl=(value)=>{try{const url=new URL(text(value));return url.protocol==='https:'?url.href:undefined}catch{return undefined}};
const eventRow=(raw)=>{const row=record(raw),location=record(row.location),address=record(location.address),performers=Array.isArray(row.performer)?row.performer.map(record):[],lead=record(performers[0]),genres=Array.isArray(lead.genre)?lead.genre.map(text).filter(Boolean):[],offers=Array.isArray(row.offers)?row.offers.map(record):[],offer=offers.find(item=>text(item.category)==='ticketingLinkPrimary')||offers[0],start=text(row.startDate),date=start?new Intl.DateTimeFormat('en-US',{weekday:'short',month:'short',day:'numeric'}).format(new Date(start)):'Date TBA',time=start.includes('T')?new Intl.DateTimeFormat('en-US',{hour:'numeric',minute:'2-digit'}).format(new Date(start)):'Time TBA';return{id:text(row.identifier)||'jambase-'+crypto.randomUUID(),name:text(row.name)||'Untitled event',date,time,venue:text(location.name)||'Venue TBA',city:[text(address.addressLocality),text(record(address.addressRegion).alternateName||record(address.addressRegion).name)].filter(Boolean).join(', ')||'Location TBA',genre:genres[0]||'Live music',artists:performers.map(item=>text(item.name)).filter(Boolean),distance:0,ticketUrl:offer?safeUrl(offer.url):undefined,source:'JamBase',image:safeUrl(row.image)||'linear-gradient(135deg,#3f2665,#d44d88)',going:0,interested:0}};
async function jamBase(path,env){const key=env.JBD_API_KEY||env.JAMBASE_API_KEY;if(!key)return json({error:'Live events are not configured.'},503);const base=(env.JBD_BASE_URL||env.JAMBASE_API_BASE_URL||'https://api.data.jambase.com/v3').replace(/\\/$/,'');let response;try{response=await fetch(base+path,{headers:{Authorization:'Bearer '+key,Accept:'application/json','User-Agent':'JamQuest/1.0'}})}catch{return json({error:'Live events are temporarily unavailable.'},502)}if(!response.ok)return json({error:response.status===429?'JamBase rate limit reached. Please try again shortly.':'Live events are temporarily unavailable.'},response.status);return response.json()}
async function events(url,env){const kind=url.searchParams.get('type')||'event',city=url.searchParams.get('geoCityId'),metro=url.searchParams.get('geoMetroId'),location=city||metro||'jambase:1';if(!/^jambase:\\d+$/.test(location)||!['event','artist','venue'].includes(kind))return json({error:'Invalid event search.'},400);const params=new URLSearchParams({perPage:'20',page:'1'});params.set(city?'geoCityId':'geoMetroId',location);const query=(url.searchParams.get('q')||'').trim();if(query)params.set(kind==='artist'?'artistName':kind==='venue'?'venueName':'name',query.slice(0,100));const data=await jamBase('/events?'+params,env);if(data instanceof Response)return data;return json({events:Array.isArray(data.events)?data.events.map(eventRow):[],pagination:record(data.pagination),refreshedAt:new Date().toISOString(),source:'JamBase'})}
async function locations(url,env){const query=(url.searchParams.get('q')||'').trim().slice(0,80);if(!query)return json({locations:[]});const data=await jamBase('/geographies/cities?'+new URLSearchParams({geoCityName:query,perPage:'8'}),env);if(data instanceof Response)return data;const locations=Array.isArray(data.cities)?data.cities.map(record).map(city=>{const region=record(city.addressRegion),country=record(city.country),name=text(city.name),id=text(city.identifier),area=text(region.alternateName)||text(region.name)||text(country.alternateName)||text(country.name);return/^jambase:\\d+$/.test(id)&&name?{id,label:[name,area].filter(Boolean).join(', ')}:null}).filter(Boolean):[];return json({locations})}
export default {async fetch(request,env){const url=new URL(request.url);if(request.method==='GET'&&url.pathname==='/api/events')return events(url,env);if(request.method==='GET'&&url.pathname==='/api/locations')return locations(url,env);const key=files[url.pathname]?url.pathname:(request.method==='GET'&&!url.pathname.includes('.')?'/index.html':url.pathname);const file=files[key];if(!file)return new Response('Not found',{status:404});return new Response(decode(file[1]),{headers:{'Content-Type':file[0],'Cache-Control':key.includes('/_next/')?'public, max-age=31536000, immutable':'no-cache'}})}};
`;
  writeFileSync(path.join(directory, "server", "index.js"), source);
}
try { if (existsSync(api)) renameSync(api, parked); execFileSync(path.join(root, "node_modules", ".bin", "next"), ["build"], { stdio: "inherit", env: { ...process.env, JAMQUEST_STATIC_BUILD: "1" } }); rmSync(path.join(root, "dist"), { recursive: true, force: true }); cpSync(path.join(root, "out"), path.join(root, "dist"), { recursive: true }); mkdirSync(path.join(root, "dist", "server"), { recursive: true }); mkdirSync(path.join(root, "dist", ".openai"), { recursive: true }); writeEmbeddedWorker(path.join(root, "dist")); cpSync(path.join(root, "scripts", "worker-hosting.json"), path.join(root, "dist", ".openai", "hosting.json")); }
finally { if (existsSync(parked)) renameSync(parked, api); }
