import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, renameSync, rmSync, statSync, writeFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import path from "node:path";
const root = process.cwd(); const api = path.join(root, "app", "api"); const parked = path.join(root, "server", ".app-api-server-only");
const contentTypes = { ".css": "text/css; charset=utf-8", ".html": "text/html; charset=utf-8", ".ico": "image/x-icon", ".js": "text/javascript; charset=utf-8", ".json": "application/json; charset=utf-8", ".svg": "image/svg+xml", ".txt": "text/plain; charset=utf-8", ".woff2": "font/woff2" };
const mimeType = (file) => contentTypes[path.extname(file)] || "application/octet-stream";
function collectStaticFiles(directory, relative = "") { return readdirSync(directory).flatMap((entry) => { const full = path.join(directory, entry); const next = path.join(relative, entry); return statSync(full).isDirectory() ? collectStaticFiles(full, next) : [[`/${next.split(path.sep).join("/")}`, [mimeType(entry), readFileSync(full).toString("base64")]]]; }); }
function writeEmbeddedWorker(directory) { const files = Object.fromEntries(collectStaticFiles(directory)); const source = `const files=${JSON.stringify(files)};\nconst decode=(value)=>Uint8Array.from(atob(value),character=>character.charCodeAt(0));\nexport default {async fetch(request){const url=new URL(request.url);const key=files[url.pathname]?url.pathname:(request.method==='GET'&&!url.pathname.includes('.')?'/index.html':url.pathname);const file=files[key];if(!file)return new Response('Not found',{status:404});return new Response(decode(file[1]),{headers:{'Content-Type':file[0],'Cache-Control':key.includes('/_next/')?'public, max-age=31536000, immutable':'no-cache'}})}};\n`; writeFileSync(path.join(directory, "server", "index.js"), source); }
try { if (existsSync(api)) renameSync(api, parked); execFileSync(path.join(root, "node_modules", ".bin", "next"), ["build"], { stdio: "inherit", env: { ...process.env, JAMQUEST_STATIC_BUILD: "1" } }); rmSync(path.join(root, "dist"), { recursive: true, force: true }); cpSync(path.join(root, "out"), path.join(root, "dist"), { recursive: true }); mkdirSync(path.join(root, "dist", "server"), { recursive: true }); mkdirSync(path.join(root, "dist", ".openai"), { recursive: true }); writeEmbeddedWorker(path.join(root, "dist")); cpSync(path.join(root, "scripts", "worker-hosting.json"), path.join(root, "dist", ".openai", "hosting.json")); }
finally { if (existsSync(parked)) renameSync(parked, api); }
